import { escapeHTML as e, money, localDate, normalizeName, safeWebsite } from '../domain.js';
import { ENVIRONMENTS, CSM_STAGES, PILLARS, MOTIONS, metrics, forecast, dataHealth, roi, sumValue, dealDate } from '../platform-domain.js';
import { createPlatformService } from './platform-service.js';

export function createPlatform(L,W,experience) {
  const service=createPlatformService(L,W), S=service.state;
  const ui={scenario:'base',pillar:0,document:null,query:'',drag:null};
  const page=()=>document.getElementById('page');
  const icon=name=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
  const refreshIcons=()=>window.lucide?.createIcons();
  const act=(label,action,extra='',primary=false)=>`<button type="button" class="btn ${primary?'btn-primary':'btn-outline'}" data-platform-action="${action}" ${extra}>${label}</button>`;
  const go=(label,route,primary=false)=>act(label,'go',`data-route="${route}"`,primary);
  const head=(title,description,actions='')=>`<div class="page-header"><div class="page-title"><h1>${e(title)}</h1><p class="page-subtitle">${e(description)}</p></div><div class="action-group">${actions}</div></div>`;
  const empty=(title,description,action='')=>`<div class="product-empty">${icon('scan-line')}<h3>${e(title)}</h3><p>${e(description)}</p>${action}</div>`;
  const field=(label,name,value='',attrs='')=>`<label class="field"><span>${e(label)}</span><input class="input" name="${name}" value="${e(value)}" ${attrs}></label>`;
  const area=(label,name,value='',hint='')=>`<label class="field"><span>${e(label)}</span><textarea class="input" name="${name}" rows="4" maxlength="12000" placeholder="${e(hint)}">${e(value)}</textarea></label>`;
  const option=(value,label,selected)=>`<option value="${e(value)}" ${value===selected?'selected':''}>${e(label)}</option>`;
  const errorBox='<p class="form-error" data-platform-error role="alert"></p>';
  const editorFooter=()=>`${errorBox}<div class="form-actions"><span class="form-note">${S.ready?'Shared with this workspace.':'Draft stays on this device until workspace storage is enabled.'}</span><button class="btn btn-primary" type="submit">${S.ready?'Save changes':'Save device draft'}</button></div>`;
  const docOf=kind=>S.documents.find(d=>d.kind===kind);
  const nameOf=id=>L.store.companies.find(c=>c.id===id)?.name||'Unlinked account';
  const person=id=>S.members.find(m=>m.user_id===id)?.display_name || (id===L.userId?'You':'Unassigned');
  const dateText=value=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric'}):'Not set';
  const compact=value=>new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(Number(value)||0);
  const pct=value=>value===null?'—':`${Math.round(value)}%`;
  function kpi(label,value,detail,symbol='chart-no-axes-combined',highlight=false){return `<article class="metric-tile ${highlight?'metric-highlight':''}"><div class="metric-label">${e(label)}${icon(symbol)}</div><strong>${e(value)}</strong><div class="metric-detail">${e(detail)}</div></article>`;}
  function renderBars(rows,{moneyValues=false}={}) {
    const max=Math.max(1,...rows.map(r=>r.value));
    return `<div class="signal-bars">${rows.map((r,i)=>`<div class="signal-bar-row"><span>${e(r.label)}</span><div class="signal-bar-track"><i class="${i===rows.length-1?'highlight-bar':''}" style="width:${Math.max(0,r.value)/max*100}%"></i></div><strong>${moneyValues?money(r.value):e(r.value)}</strong></div>`).join('')}</div>`;
  }
  function stageChart(){
    const rows=L.stages.filter(s=>!['Won','Lost'].includes(s.key)).map(s=>({label:s.key,value:sumValue(L.store.deals.filter(d=>d.stage===s.key))}));
    const max=Math.max(1,...rows.map(r=>r.value));
    return `<div class="stage-chart" role="img" aria-label="Open pipeline by stage: ${e(rows.map(r=>`${r.label} ${money(r.value)}`).join(', '))}"><div class="stage-axis"><span>${money(max)}</span><span>${money(max/2)}</span><span>SAR 0</span></div><div class="stage-columns">${rows.map((r,i)=>`<div class="stage-column"><strong>${compact(r.value)}</strong><div class="stage-column-track"><i style="height:${r.value/max*100}%;--column-color:${['#b7a3dc','#a580eb','#8B57F1','#D249D9','#F9FE56'][i%5]}"></i></div><span>${e(r.label)}</span></div>`).join('')}</div></div>`;
  }
  function followups(limit=5){
    const rows=metrics(L.store).due.sort((a,b)=>a.next_action_due.localeCompare(b.next_action_due)).slice(0,limit);
    return rows.length?`<div class="focus-list">${rows.map(a=>`<button class="focus-row" data-platform-action="account" data-id="${e(a.company_id)}"><span class="focus-date">${a.next_action_due<localDate()?'Overdue':'Today'}</span><span><strong>${e(a.next_action)}</strong><small>${e(nameOf(a.company_id))}</small></span>${icon('arrow-up-right')}</button>`).join('')}</div>`:empty('You’re up to date','No overdue next actions. Open an account to plan your next touchpoint.',go('Open companies','companies'));
  }
  function home(target){
    const m=metrics(L.store), env=ENVIRONMENTS[S.environment]||ENVIRONMENTS.sales, targetValue=L.store.targets.annual_sar;
    const title={executive:'The revenue picture. Clear.',commercial:'Your revenue, in focus.',sales:'Make your next move count.'}[S.environment];
    target.innerHTML=head('Command Center',env.objective,S.access.writeCRM?go(`${icon('plus')} New opportunity`,'companies',true):'')
      +`<section class="command-intro"><div><h2>${title}</h2><p>${m.due.length ? `${m.due.length} follow-up${m.due.length===1?'':'s'} need attention. Keep your team focused on the next decision.`:'Your accounts, pipeline and next actions in one place.'}</p></div><div class="command-actions">${go(`${icon('sparkles')} Open iHelper`,'helper')}${go('Review forecast','forecast')}</div></section>`
      +`<div class="metric-grid">${kpi('Active pipeline',money(m.pipeline),`${m.open.length} open opportunities`,'chart-no-axes-combined')}${kpi('Won revenue · YTD',money(m.wonValue),targetValue?`${pct(m.wonValue/targetValue*100)} of annual target`:'Set your annual target to measure progress','trophy',true)}${kpi('Win rate',pct(m.winRate),`${m.won.length} won / ${m.closed.length} closed · all time`,'crosshair')}${S.environment==='sales'?kpi('Actions due',String(m.due.length),'Open a follow-up to act','calendar-check'):kpi('Weighted pipeline',money(m.weighted),'Using saved opportunity probabilities','scale')}</div>`
      +`<div class="command-grid"><section class="panel"><div class="panel-heading"><div><h2>Pipeline composition</h2><p>Where your active revenue sits today</p></div>${go('View CRM','crm')}</div>${stageChart()}<div class="panel-foot"><span>${m.open.length} open opportunities</span><strong>${money(m.pipeline)} total</strong></div></section><section class="panel"><div class="panel-heading"><div><h2>Needs your attention</h2><p>Next actions across your workspace</p></div>${icon('calendar-clock')}</div>${followups()}</section></div>`
      +`<div class="command-lower"><section class="panel"><div class="panel-heading"><div><h2>Deals to focus on</h2><p>Highest-value open opportunities</p></div>${go('All opportunities','crm')}</div>${dealTable([...m.open].sort((a,b)=>b.value_sar-a.value_sar).slice(0,5))}</section><section class="activation-panel"><h2>A useful next step.<br>Every account.</h2><p>Connect a company, an opportunity and a dated next action to make your workspace actionable.</p>${go('Review your setup','onboarding')}${go('Invite your team','workspace')}</section></div>`;
  }
  function dealTable(rows, forecastDates=false){return rows.length?`<div class="table-wrap"><table class="datatable"><thead><tr><th>Opportunity / account</th><th>Stage</th><th>Value</th><th>Probability</th><th>${forecastDates?'Forecast date':'Expected close'}</th></tr></thead><tbody>${rows.map(d=>`<tr><td><button class="text-button" data-platform-action="account" data-id="${e(d.company_id)}">${e(d.name)}</button><small>${e(nameOf(d.company_id))}</small></td><td><span class="stage-badge">${e(d.stage)}</span><small>${e(d.sub_stage)}</small></td><td class="numeric">${money(d.value_sar)}</td><td>${pct(Number(d.probability)||0)}</td><td>${dateText(forecastDates&&d.stage==='Won'?d.actual_close||dealDate(d):dealDate(d))}</td></tr>`).join('')}</tbody></table></div>`:empty('No opportunities in this view','Add an opportunity to an account to start building your pipeline.',go('Open companies','companies'));}
  function forecastPage(target){
    const values=Object.fromEntries(['base','aggressive','conservative'].map(k=>[k,forecast(L.store.deals,k)])), f=values[ui.scenario];
    const max=Math.max(1,...Object.values(values).flatMap(v=>v.buckets.map(b=>b.cumulative)));
    const points=f.buckets.map((b,i)=>`${60+i*150},${260-b.cumulative/max*215}`).join(' ');
    target.innerHTML=head('Revenue Forecast','A six-month planning view, built from saved deal values, close dates and probabilities.',act(`${icon('download')} Export forecast`,'export-forecast'))
      +`<section class="forecast-overview"><div><h2>Plan for the possibilities.</h2><p>Change the scenario to test probability assumptions.</p></div><div class="scenario-switch" role="group" aria-label="Forecast scenario">${Object.entries(values).map(([k,v])=>`<button aria-pressed="${ui.scenario===k}" data-platform-action="scenario" data-scenario="${k}"><span>${{base:'Base case',aggressive:'Aggressive',conservative:'Conservative'}[k]}</span><strong>${money(v.total)}</strong></button>`).join('')}</div></section>`
      +`<section class="panel forecast-panel"><div class="panel-heading"><div><h2>Cumulative projected revenue</h2><p>${e(f.buckets[0].label)} – ${e(f.buckets.at(-1).label)} · SAR</p></div><span class="source-label">Planning model · not an AI prediction</span></div><div class="forecast-svg"><svg viewBox="0 0 880 310" role="img" aria-label="${e(f.buckets.map(b=>`${b.label}: ${money(b.cumulative)}`).join('; '))}">${[0,.25,.5,.75,1].map(r=>`<line x1="60" x2="810" y1="${260-r*215}" y2="${260-r*215}" class="chart-gridline"/><text x="3" y="${265-r*215}" class="chart-label">${compact(max*r)}</text>`).join('')}<polygon points="60,260 ${points} 810,260" class="forecast-area"/><polyline points="${points}" class="forecast-line"/>${f.buckets.map((b,i)=>`<circle cx="${60+i*150}" cy="${260-b.cumulative/max*215}" r="5" class="forecast-point"><title>${e(b.label)}: ${money(b.cumulative)}</title></circle><text x="${60+i*150}" y="299" text-anchor="middle" class="chart-label">${e(b.label)}</text>`).join('')}</svg></div><div class="forecast-months">${f.buckets.map(b=>`<div><span>${e(b.label)}</span><strong>${money(b.value)}</strong><small>Projected this month</small></div>`).join('')}</div></section>`
      +`<div class="metric-grid">${kpi('Scenario total',money(f.total),'Within the six-month window','chart-no-axes-combined',true)}${kpi('Probability adjustment',`${f.offset>0?'+':''}${f.offset} pts`,'Applied to open deals; capped at 0–100%','sliders-horizontal')}${kpi('Overdue close dates',String(f.overdue),'Excluded until a new expected close is set','calendar-clock')}${kpi('Missing close dates',String(f.undated),'Add a date to include these opportunities','calendar-x')}</div><section class="panel"><div class="panel-heading"><div><h2>Forecast contributors</h2><p>Won deals use 100%; open deals use scenario-adjusted saved probabilities. Overdue open deals are excluded.</p></div></div>${dealTable(L.store.deals.filter(d=>{const date=d.stage==='Won'?String(d.actual_close||dealDate(d)):dealDate(d);return d.stage!=='Lost'&&(d.stage==='Won'||date>=localDate())&&f.buckets.some(b=>b.key===date.slice(0,7));}),true)}</section>`;
  }
  function crmAnalytics(target){const m=metrics(L.store);target.innerHTML=head('CRM Analytics','Pipeline, conversion and revenue from your workspace.',go('Open CRM board','crm'))+`<div class="metric-grid">${kpi('Open pipeline',money(m.pipeline),`${m.open.length} opportunities`)}${kpi('Won revenue',money(m.wonTotal),'All recorded won deals','trophy',true)}${kpi('Win rate',pct(m.winRate),`${m.closed.length} closed opportunities`,'crosshair')}${kpi('Average won deal',m.won.length?money(m.wonTotal/m.won.length):'—','Based on recorded wins','scale')}</div><div class="command-grid"><section class="panel"><div class="panel-heading"><h2>Pipeline by stage</h2></div>${stageChart()}</section><section class="panel"><div class="panel-heading"><h2>Revenue by account</h2></div>${renderBars(L.store.companies.map(c=>({label:c.name,value:sumValue(m.open.filter(d=>d.company_id===c.id))})).filter(c=>c.value).sort((a,b)=>b.value-a.value).slice(0,6),{moneyValues:true})}</section></div><section class="panel"><div class="panel-heading"><h2>Open opportunity detail</h2></div>${dealTable(m.open)}</section>`;}
  function customers(){return L.store.deals.filter(d=>d.stage==='Won').map(d=>({...d,success:S.customers.find(c=>c.deal_id===d.id)}));}
  function csmAnalytics(target){
    const rows=customers(), assessed=rows.filter(d=>d.success?.health && d.success.health!=='Not assessed'), atRisk=rows.filter(d=>d.success?.health==='At risk');
    const next90=new Date();next90.setDate(next90.getDate()+90);
    const renewals=rows.filter(d=>d.success?.renewal_date>=localDate()&&d.success.renewal_date<=localDate(next90));
    const regions=new Map();rows.forEach(d=>{const c=L.store.companies.find(c=>c.id===d.company_id),region=c?.city||c?.country||'Location missing';regions.set(region,(regions.get(region)||0)+1);});
    target.innerHTML=head('CSM Analytics','Customer success begins with a won deal. Health and renewal dates are recorded by your team.',go('Open CSM board','csm'))+`<div class="metric-grid">${kpi('Customer accounts',String(new Set(rows.map(d=>d.company_id)).size),'Unique accounts with won deals','building-2')}${kpi('Won contract value',money(sumValue(rows)),'Contract value, not recurring revenue','trophy',true)}${kpi('At-risk contracts',String(atRisk.length),`${assessed.length} of ${rows.length} health assessments recorded`,'heart-pulse')}${kpi('Renewals · next 90 days',String(renewals.length),'Uses explicitly recorded renewal dates','calendar-clock')}</div><div class="command-grid"><section class="panel"><div class="panel-heading"><h2>Customer lifecycle</h2></div>${renderBars(CSM_STAGES.map(s=>({label:s.key,value:rows.filter(d=>(d.success?.stage||'Onboarding')===s.key).length})))}</section><section class="panel"><div class="panel-heading"><div><h2>Regional coverage</h2><p>Won contracts by recorded city or country</p></div>${icon('map-pinned')}</div>${regions.size?renderBars([...regions].map(([label,value])=>({label,value}))):empty('Your footprint starts with a win','Add locations to company records to see your coverage.')}</section></div><section class="panel"><div class="panel-heading"><h2>Customer portfolio</h2></div>${dealTable(rows)}</section>`;
  }
  function activitiesAnalytics(target){const types=['Call','Meeting','Demo','Email','LinkedIn','Proposal'], start=new Date();start.setDate(start.getDate()-29);const rows=L.store.activities.filter(a=>(a.date||a.activity_date)>=localDate(start)&&(a.date||a.activity_date)<=localDate());target.innerHTML=head('Activities Momentum','Understand the work that moves relationships forward. Last 30 calendar days.',go('Log an activity','activities',true))+`<div class="metric-grid">${kpi('Activities logged',String(rows.length),'Last 30 days','activity')}${kpi('Calls & meetings',String(rows.filter(a=>['Call','Meeting'].includes(a.type)).length),'Relationship-building touchpoints','phone')}${kpi('Demos',String(rows.filter(a=>a.type==='Demo').length),'Product conversations','presentation')}${kpi('Follow-ups due',String(metrics(L.store).due.length),'Today and overdue','calendar-check',true)}</div><div class="command-grid"><section class="panel"><div class="panel-heading"><h2>Activity mix</h2></div>${renderBars(types.map(type=>({label:type,value:rows.filter(a=>a.type===type).length})))}</section><section class="panel"><div class="panel-heading"><h2>Follow-through</h2></div>${followups()}</section></div>`;}
  function healthPage(target){const h=dataHealth(L.store);target.innerHTML=head('Data Health','Find missing information before it slows your team down. Completeness is not external verification.',go('Companies','companies')+go('Contacts','people'))+`<div class="metric-grid">${kpi('Field completeness',pct(h.score),'Six core company and contact fields','shield-check',true)}${kpi('Duplicate company names',String(h.companyDuplicates),'Normalized name matches','copy')}${kpi('Duplicate contact emails',String(h.emailDuplicates),'Exact normalized email matches','mails')}${kpi('Invalid email formats',String(h.invalidEmails),'Format check only; deliverability unknown','mail-warning')}</div><section class="panel"><div class="panel-heading"><h2>What needs attention</h2></div><div class="health-list">${h.rows.map(r=>`<div class="health-row"><div><strong>${e(r.label)}</strong><small>${r.complete} of ${r.total} records complete</small></div><progress value="${r.complete}" max="${r.total||1}"></progress><strong>${pct(r.total?r.complete/r.total*100:null)}</strong>${go('Review',r.route)}</div>`).join('')}</div></section>`;}
  function helperPage(target){
    const m=metrics(L.store),h=dataHealth(L.store),env=ENVIRONMENTS[S.environment]||ENVIRONMENTS.sales;
    const items=S.environment==='executive' ? [['Revenue exposure',`${money(m.pipeline)} in open pipeline; ${money(m.weighted)} after saved probability weighting.`,'forecast'],['Customer continuity',`${m.won.length} won contracts. Review customer health and renewal readiness.`,'reportCSM'],['Strategic alignment','Compare the commercial plan with the vision and annual target.','target']] : S.environment==='commercial' ? [['Pipeline quality',`${m.open.length} open deals. Prioritize late-stage opportunities and missing next actions.`,'crm'],['Team momentum',`${m.due.length} next actions are due. Review your team’s follow-through.`,'reportActivity'],['GTM alignment','Keep segmentation, proof and growth motions aligned with your pipeline.','gtm']] : [['Your next conversations',`${m.due.length} follow-ups need attention. Start with the oldest overdue action.`,'activities'],['Prepare for objections','Open your team’s battlecards before your next customer conversation.','battlecards'],['Build the business case','Turn the buyer’s assumptions into a transparent value estimate.','roi']];
    target.innerHTML=head('iHelper',`${env.name}: resources, key insights and objectives grounded in your saved data.`)+`<section class="helper-intro"><div class="helper-symbol">${icon('sparkles')}</div><div><h2>What deserves your attention?</h2><p>A practical briefing from your workspace. These are rule-based insights, not generated research.</p></div></section><form id="helperQuery" data-platform-form="helper" class="helper-query"><label class="sr-only" for="helperQuestion">Ask about your workspace</label><input id="helperQuestion" class="input" name="question" required placeholder="Ask about pipeline, targets, customers, or data quality"><button class="btn btn-primary">Find insight ${icon('arrow-right')}</button></form><div id="helperAnswer" role="status"></div><div class="insight-grid">${items.map(([title,copy,route])=>`<section class="panel insight-panel"><h2>${e(title)}</h2><p>${e(copy)}</p>${go('Review insight '+icon('arrow-up-right'),route)}</section>`).join('')}</div><section class="panel"><div class="panel-heading"><div><h2>Workspace context</h2><p>Use an account’s AI brief when you need a company-specific draft.</p></div>${go('Choose an account','companies')}</div><div class="context-strip"><span>${L.store.companies.length} companies</span><span>${L.store.contacts.length} contacts</span><span>${pct(h.score)} core-field completeness</span></div></section>`;
  }
  function board(target,type){
    const isCSM=type==='csm', stages=isCSM?CSM_STAGES:L.stages,rows=isCSM?customers():L.store.deals;
    target.innerHTML=head(isCSM?'CSM':'CRM',`Drag ${isCSM?'won contracts':'deals'} between stages. Every move requires a sub-stage confirmation.`,isCSM?go('CSM analytics','reportCSM'):S.access.writeCRM?go(`${icon('plus')} New opportunity`,'companies',true):'')
      +(isCSM&&!S.ready?'<p class="notice-bar">Customer tracking is available after the database upgrade. Won deals remain visible here.</p>':'')
      +`<div class="board-tools"><span>${rows.length} ${isCSM?'won contracts':'opportunities'} · ${money(sumValue(rows))}</span><span>${S.access.writeCRM?'Use Move on any card for keyboard and touch access.':'Read-only access · your administrator controls editing permissions.'}</span></div><div class="revenue-board" data-board="${type}">${stages.map((s,i)=>{const group=rows.filter(d=>(isCSM?d.success?.stage||'Onboarding':d.stage)===s.key);return `<section class="revenue-column" data-drop-stage="${e(s.key)}"><div class="revenue-column-heading"><span class="column-dot" style="--column-color:${['#8B57F1','#a580eb','#D249D9','#c9b2f3','#F9FE56','#9fb9ac','#c27e85'][i%7]}"></span><h2>${e(s.key)}</h2><span>${group.length}</span></div><div class="column-total">${money(sumValue(group))}</div><div class="revenue-cards">${group.map(d=>`<article class="revenue-card" data-deal="${e(d.id)}" draggable="${S.access.writeCRM&&(!isCSM||S.ready)}"><span class="card-account">${e(nameOf(d.company_id))}</span><button class="text-button deal-title" data-platform-action="account" data-id="${e(d.company_id)}">${e(d.name)}</button><strong class="deal-value">${money(d.value_sar)}</strong><span class="stage-badge">${e(isCSM?d.success?.sub_stage||'Handoff pending':d.sub_stage||'Sub-stage not set')}</span><div class="deal-meta"><span>${icon(isCSM?'heart-pulse':'calendar')}${e(isCSM?d.success?.health||'Not assessed':dateText(dealDate(d)))}</span><span>${e(person(d.assigned_to||d.owner_id))}</span></div>${S.access.writeCRM?act(`${icon('move-right')} Move${isCSM?' / update':''}`,'move',`data-id="${e(d.id)}" data-type="${type}" ${isCSM&&!S.ready?'disabled':''}`):''}</article>`).join('')||'<p class="column-empty">No deals in this stage</p>'}</div></section>`;}).join('')}</div>`;
  }
  function moveDialog(id,type,stage){
    if(!S.access.writeCRM)throw new Error('Your role has read-only access.');
    const d=L.store.deals.find(d=>d.id===id);if(!d)throw new Error('This opportunity is no longer available.');
    const c=S.customers.find(c=>c.deal_id===id),stages=type==='csm'?CSM_STAGES:L.stages,current=stage||(type==='csm'?c?.stage||'Onboarding':d.stage);
    document.getElementById('platformDialog')?.remove();const dialog=document.createElement('dialog');dialog.id='platformDialog';dialog.className='platform-dialog';
    dialog.innerHTML=`<form data-platform-form="move" data-id="${e(id)}" data-type="${type}" data-original-stage="${e(d.database_stage||d.stage)}" data-original-sub="${e(d.sub_stage||'')}" data-updated="${e(c?.updated_at||'')}"><div class="panel-heading"><div><h2>Confirm the next stage</h2><p>${e(d.name)}</p></div>${act(icon('x'),'close-dialog','aria-label="Close stage confirmation"')}</div><div class="form-grid"><label class="field"><span>Stage</span><select class="input" id="moveStage" name="stage">${stages.map(s=>option(s.key,s.key,current)).join('')}</select></label><label class="field"><span>Sub-stage (required)</span><select class="input" id="moveSubstage" name="sub_stage" required><option value="">Choose a sub-stage</option>${stages.find(s=>s.key===current).subs.map(sub=>option(sub,sub,'')).join('')}</select></label>${type==='csm'?`<label class="field"><span>Customer health</span><select class="input" name="health">${['Not assessed','Healthy','Watch','At risk'].map(s=>option(s,s,c?.health||'Not assessed')).join('')}</select></label>${field('Renewal date','renewal_date',c?.renewal_date||'','type="date"')}`:''}</div>${type==='csm'?area('Success notes','notes',c?.notes||''):''}<p class="form-note">Nothing changes until you confirm. Cancel to keep the current stage.</p>${errorBox}<div class="form-actions">${act('Cancel','close-dialog')}<button type="submit" class="btn btn-primary">Confirm change</button></div></form>`;
    document.body.append(dialog);dialog.showModal();refreshIcons();dialog.addEventListener('change',event=>{if(event.target.id==='moveStage'){const s=stages.find(s=>s.key===event.target.value);dialog.querySelector('#moveSubstage').innerHTML='<option value="">Choose a sub-stage</option>'+s.subs.map(sub=>option(sub,sub,'')).join('');}});
  }
  function gtmPage(target){
    const doc=docOf('gtm'),content=doc?.content||{},key=PILLARS[ui.pillar],value=content[key]||'';
    target.innerHTML=head('GTM Strategy','One shared strategy, from your target market to the way you package value.',go('Growth motions','motions'))+`<div class="strategy-layout"><nav class="pillar-nav" aria-label="Strategy pillars">${PILLARS.map((p,i)=>`<button data-platform-action="pillar" data-index="${i}" aria-current="${i===ui.pillar?'page':'false'}">${icon(content[p]?'circle-check':'circle')}<span>${e(p)}</span></button>`).join('')}</nav><section class="panel strategy-editor"><div class="panel-heading"><div><h2>${e(key)}</h2></div><span class="source-label">${PILLARS.filter(p=>content[p]).length} / ${PILLARS.length} documented</span></div><form data-platform-form="gtm">${area('Your strategy','body',value,`Document your ${key.toLowerCase()}: decisions, evidence, ownership and the next review.`)}${S.access.writeStrategy?editorFooter():'<p class="form-note">View access. Your commercial lead maintains the shared strategy.</p>'}</form><div class="strategy-prompts"><strong>Make the decision explicit</strong><p>Who are we focusing on? What evidence supports this choice? Who owns the next action?</p></div></section></div>`;
    if(!S.access.writeStrategy)target.querySelector('textarea').readOnly=true;
  }
  function motionsPage(target){const d=docOf('motions'),c=d?.content||{},mix=c.mix||[25,25,25,25];target.innerHTML=head('GTM Motions Mix','Decide how your team will attract, convert and expand customers. Percentages are planning allocations.')+`<form data-platform-form="motions" class="motions-form"><div class="motion-grid">${MOTIONS.map((m,i)=>`<section class="panel motion-card"><div class="panel-heading"><h2>${e(m)}</h2>${icon(['handshake','megaphone','network','mouse-pointer-2'][i])}</div><label class="field"><span>Allocation (%)</span><input class="input mix-input" name="mix${i}" type="number" min="0" max="100" step="1" value="${e(mix[i])}" required></label>${area('Objective & next experiment',`note${i}`,c.notes?.[i]||'',['Define the target account and sales play.','Define the demand-creation program.','Define the partner and joint value.','Define activation, invitations and expansion triggers.'][i])}</section>`).join('')}</div><section class="panel"><div class="mix-meter">${mix.map((v,i)=>`<i style="width:${Number(v)||0}%;--mix-color:${['#8B57F1','#D249D9','#b7a3dc','#F9FE56'][i]}"></i>`).join('')}</div><p id="mixTotal" role="status">Total allocation: ${mix.reduce((a,b)=>a+Number(b),0)}% · Must equal 100% to save.</p>${S.access.writeStrategy?editorFooter():''}</section></form>`;if(!S.access.writeStrategy)target.querySelectorAll('input,textarea').forEach(x=>x.disabled=true);}
  function battlecardsPage(target){const rows=S.documents.filter(d=>d.kind==='battlecard');target.innerHTML=head('Battlecards','Make comparisons useful: documented differences, buyer questions and evidence.',S.access.writeStrategy?act(`${icon('plus')} New battlecard`,'new-battlecard','',true):'')+(rows.length?`<div class="artifact-grid">${rows.map(d=>`<article class="panel artifact-card"><div class="artifact-cover">${icon('swords')}<span>Comparative analysis</span></div><h2>${e(d.title)}</h2><p>${e(d.content.position||'Add your point of differentiation.')}</p><small>${d.local_draft?'Device draft':'Workspace artifact'} · ${dateText(d.updated_at)}</small><div class="action-group">${act('Open battlecard','edit-battlecard',`data-id="${e(d.id)}"`)}${act(icon('download'),'export-document',`data-id="${e(d.id)}" aria-label="Export ${e(d.title)}"`)}</div></article>`).join('')}</div>`:empty('Give your team a point of view','Create a comparison from evidence you can stand behind. No competitor claims are generated automatically.',S.access.writeStrategy?act('Create battlecard','new-battlecard','',true):''));}
  function battlecardEditor(target){const d=S.documents.find(d=>d.id===ui.document),c=d?.content||{};target.innerHTML=head(d?.title||'New battlecard','A shared, evidence-led comparison for your sales conversations.',go('All battlecards','battlecards'))+`<form data-platform-form="battlecard" class="panel artifact-editor">${field('Title','title',d?.title||'','required maxlength="160" placeholder="Your solution vs. alternative"')}<div class="form-grid">${area('Our positioning','position',c.position||'')}${area('Alternative strengths','strengths',c.strengths||'')}${area('Trade-offs and gaps','gaps',c.gaps||'')}${area('Buyer questions','questions',c.questions||'')}${area('Proof and sources','proof',c.proof||'')}${area('When to use this comparison','context',c.context||'')}</div>${S.access.writeStrategy?editorFooter():''}</form>`;if(!S.access.writeStrategy)target.querySelectorAll('input,textarea').forEach(x=>x.readOnly=true);}
  function roiPage(target){const d=S.documents.find(d=>d.id===ui.document&&d.kind==='roi'),c=d?.content||{people:10,hours:2,hourly:150,benefit:0,setup:25000,annual:30000};target.innerHTML=head('ROI Calculator & Case Studies','Build a transparent business case. Every result depends on the assumptions you enter.')+`<div class="roi-layout"><form data-platform-form="roi" class="panel roi-form"><div class="panel-heading"><h2>Your assumptions</h2><span class="source-label">Illustrative inputs · editable</span></div>${field('Case study title','title',d?.title||'','required maxlength="160" placeholder="Account or business case"')}<div class="form-grid">${[['People affected','people'],['Hours saved / person / week','hours'],['Hourly cost (SAR)','hourly'],['Other annual benefit (SAR)','benefit'],['One-time investment (SAR)','setup'],['Annual recurring cost (SAR)','annual']].map(([label,key])=>field(label,key,c[key]??0,'type="number" min="0" step="0.01" required data-roi-input')).join('')}</div>${S.access.writeCRM?editorFooter():''}</form><section class="roi-results" id="roiResults" aria-live="polite"></section></div><section class="panel"><div class="panel-heading"><h2>Saved business cases</h2></div>${S.documents.filter(d=>d.kind==='roi').map(d=>`<div class="work-row"><div><strong>${e(d.title)}</strong><small>${d.local_draft?'Device draft':'Workspace case'} · ${dateText(d.updated_at)}</small></div>${act('Open','open-roi',`data-id="${e(d.id)}"`)}${act('Export','export-document',`data-id="${e(d.id)}"`)}</div>`).join('')||'<p class="form-note">Save a named case to compare it with future opportunities. No customer results are assumed.</p>'}</section>`;updateROI();}
  function updateROI(){const form=page().querySelector('.roi-form');if(!form)return;const box=document.getElementById('roiResults');try{const r=roi(Object.fromEntries(new FormData(form)));box.innerHTML=`<p class="result-heading">Estimated first-year outcome</p><h2>${money(r.net)}</h2><p>Net benefit after first-year costs</p><dl><dt>Annual gross benefit</dt><dd>${money(r.savings)}</dd><dt>First-year investment</dt><dd>${money(r.investment)}</dd><dt>First-year ROI</dt><dd>${pct(r.percent)}</dd><dt>Setup cost payback</dt><dd>${r.payback===null?'No positive recurring net benefit':`${r.payback.toFixed(1)} months`}</dd></dl><p class="form-note">52 working weeks. Gross benefit = people × weekly hours saved × hourly cost × 52 + other benefit. ROI = net benefit ÷ first-year investment. These are estimates, not achieved results.</p>`;}catch(error){box.textContent=error.message;}}
  function targetPage(target){const d=docOf('vision');target.innerHTML=head('Vision & Targets','Connect your team’s direction with a measurable revenue objective.')+`<div class="command-grid"><form class="panel" data-platform-form="vision"><div class="panel-heading"><h2>Your commercial vision</h2></div>${area('Vision, objectives and review cadence','body',d?.content?.body||'')}${S.access.writeStrategy?editorFooter():''}</form><form class="panel" data-platform-form="target"><div class="panel-heading"><h2>${new Date().getFullYear()} revenue target</h2></div>${field('Annual target (SAR)','amount',L.store.targets.annual_sar,'type="number" min="0" step="0.01" required')}<p class="form-note">This updates the workspace’s annual revenue target used by the Command Center.</p>${errorBox}${S.access.writeStrategy?'<button class="btn btn-primary">Save target</button>':''}</form></div>`;if(!S.access.writeStrategy)target.querySelectorAll('input,textarea').forEach(x=>x.readOnly=true);}
  function peoplePage(target,stakeholders=false){const q=normalizeName(ui.query),rows=L.store.contacts.filter(p=>(!stakeholders||/chief|c-suite|c-level|ceo|cfo|coo|cto|cio|president|director|vp|vice president/i.test(`${p.seniority||''} ${p.title||''}`))&&normalizeName(`${p.first_name} ${p.last_name} ${p.title} ${nameOf(p.company_id)}`).includes(q));target.innerHTML=head(stakeholders?'Stakeholders · C-Suite':'Contacts',stakeholders?'Buying-center leaders identified from recorded titles and seniority.':'The people behind your accounts.',S.access.writeCRM?act(`${icon('plus')} Add contact`,'add-contact','',true):'')+`<div class="directory-tools"><input class="input" id="platformPeopleSearch" aria-label="Search contacts" placeholder="Search name, role or company" value="${e(ui.query)}"><span>${rows.length} contacts</span></div>`+(rows.length?`<section class="panel"><div class="table-wrap"><table class="datatable"><thead><tr><th>Contact</th><th>Title</th><th>Company</th><th>Email</th><th>Phone</th></tr></thead><tbody>${rows.map(p=>`<tr><td>${S.access.writeCRM?`<button class="text-button" data-platform-action="edit-contact" data-id="${e(p.id)}">${e(`${p.first_name||''} ${p.last_name||''}`)}</button>`:e(`${p.first_name||''} ${p.last_name||''}`)}</td><td>${e(p.title||'Not set')}</td><td><button class="text-button" data-platform-action="account" data-id="${e(p.company_id)}">${e(nameOf(p.company_id))}</button></td><td>${e(p.email||'Not set')}</td><td>${e(p.phone||p.mobile||'Not set')}</td></tr>`).join('')}</tbody></table></div></section>`:empty('No matching contacts','Add contacts and their titles to build a useful buying-center view.'));}
  function activitiesPage(target){target.innerHTML=head('Activities','Log conversations and keep the next step connected to the account.',S.access.writeCRM?act(`${icon('plus')} Log activity`,'add-activity','',true):'')+`<section class="panel">${L.store.activities.length?L.store.activities.map(a=>`<div class="work-row"><span class="activity-type">${icon(a.type==='Call'?'phone':a.type==='Meeting'?'calendar':'activity')}</span><div><strong>${e(a.summary||a.type)}</strong><small>${e(a.type)} · ${dateText(a.date||a.activity_date)} · ${e(nameOf(a.company_id))}</small>${a.next_action?`<p>${e(a.next_action)} · ${dateText(a.next_action_due)} ${a.next_action_completed_at?'· Completed':''}</p>`:''}</div>${act('View account','account',`data-id="${e(a.company_id)}"`)}</div>`).join(''):empty('Start with a conversation','Log a call, meeting or demo to give your team context.')}</section>`;}
  const baseWorkspace=L.routes.workspace.render;
  function workspacePage(target){baseWorkspace(target);const active=W.state.active;if(!active)return;target.insertAdjacentHTML('afterbegin',`<section class="panel access-panel"><div class="panel-heading"><div><h2>Roles & environments</h2><p>The workspace creator is the administrator. Environment selection changes the view; it never grants permissions.</p></div>${icon('shield-check')}</div>${!S.ready?'<p class="notice-bar">Role assignment becomes available after the database upgrade. Current membership access remains in effect.</p>':S.members.map(m=>`<form class="member-access" data-platform-form="access" data-user="${e(m.user_id)}"><div><strong>${e(m.display_name)}</strong><small>${m.user_id===L.userId?'You':e(m.role)}</small></div><label class="field"><span>Workspace role</span><select class="input" name="role">${['member','admin',...(m.role==='owner'?['owner']:[])].map(v=>option(v,v[0].toUpperCase()+v.slice(1),m.role)).join('')}</select></label><label class="field"><span>Functional role</span><select class="input" name="app_role">${[['c_suite','Stakeholder'],['cco','Commercial Head'],['sales_rep','Sales Rep']].map(([v,l])=>option(v,l,m.app_role||'sales_rep')).join('')}</select></label><fieldset><legend>Accessible environments</legend>${Object.entries(ENVIRONMENTS).map(([key,env])=>`<label><input type="checkbox" name="environment" value="${key}" ${(m.environments||['sales']).includes(key)?'checked':''}> ${e(env.short)}</label>`).join('')}</fieldset>${S.access.admin&&m.user_id!==L.userId&&m.role!=='owner'?'<button class="btn btn-primary">Save access</button>':'<span class="source-label">'+(m.role==='owner'?'Owner protected':'View only')+'</span>'}${errorBox}</form>`).join('')}</section>`);target.querySelectorAll('.member-access').forEach(form=>{const m=S.members.find(m=>m.user_id===form.dataset.user);if(!S.access.admin||m.user_id===L.userId||m.role==='owner')form.querySelectorAll('select,input').forEach(el=>el.disabled=true);});}
  const routeGroups=[
    {label:'',key:'command',items:[['home','Command Center','layout-dashboard']]},
    {label:'Analytics Intelligence',key:'analytics',items:[['reportCRM','CRM Analytics','chart-column'],['reportCSM','CSM Analytics','heart-pulse'],['reportActivity','Activities Momentum','activity'],['reportCC','Data Health','shield-check']]},
    {label:'Sales Intelligence',key:'intelligence',items:[['helper','iHelper','sparkles'],['forecast','Revenue Forecast','chart-no-axes-combined'],['battlecards','Battlecards','swords'],['roi','ROI & Case Studies','calculator'],['crm','CRM','columns-3'],['csm','CSM','handshake']]},
    {label:'Core Intelligence',key:'strategy',items:[['gtm','GTM Strategy','compass'],['motions','GTM Motions Mix','network'],['target','Vision & Targets','crosshair']]},
    {label:'Data',key:'data',items:[['stakeholders','Stakeholders · C-Suite','landmark'],['workspace','Team & Workspaces','users-round'],['target','Vision & Targets','crosshair'],['companies','Companies','building-2'],['people','Contacts','contact'],['activities','Activity Log','calendar-days']]},
    {label:'Settings',key:'settings',items:[['billing','Usage & Plan','wallet'],['workspace','Team & Workspace','settings-2']]},
  ];
  function allowedRoute(key){if(!S.environment)return ['workspace','billing','settings'].includes(key);if(S.environment==='sales'&&['stakeholders','gtm','motions','target'].includes(key))return false;return true;}
  function shell(){
    document.getElementById('quickAddBtn').hidden=!S.access.writeCRM;
    const select=document.getElementById('environmentSelect');select.innerHTML=S.access.environments.map(key=>option(key,ENVIRONMENTS[key].name,S.environment)).join('');select.disabled=S.access.environments.length<2;
    const context=document.getElementById('environmentContext');context.textContent=ENVIRONMENTS[S.environment]?.short||'Access pending';
    document.getElementById('workspaceRole').textContent=S.access.admin?'Administrator':({c_suite:'Stakeholder',cco:'Commercial Head',sales_rep:'Sales Rep'}[S.access.role]||'Member');
    document.querySelector('#themeToggle').setAttribute('aria-label',document.documentElement.dataset.theme==='dark'?'Switch to light mode':'Switch to dark mode');
    document.querySelectorAll('.section-header').forEach(el=>{if(!el.dataset.keyboardBound){el.dataset.keyboardBound='1';el.addEventListener('keydown',event=>{if(event.key===' '||event.key==='Enter'){event.preventDefault();el.click();}});}});
    document.querySelectorAll('.nav-item').forEach(el=>{el.hidden=!allowedRoute(el.dataset.route);el.setAttribute('aria-current',el.dataset.route===L.router.current?'page':'false');});
    document.querySelectorAll('.nav-section').forEach(el=>{el.hidden=![...el.querySelectorAll('.nav-item')].some(n=>!n.hidden);});
    if(!S.access.writeCRM){page().querySelectorAll('[data-action="edit-company"],[data-action="new-contact"],[data-action="edit-contact"],[data-action="edit-deal"],[data-action="new-deal"],[data-action="new-followup"],[data-action="new-company"],[data-action="import"],[data-action="complete-followup"]').forEach(el=>el.hidden=true);}
    refreshIcons();
  }
  function download(name,content,type='text/plain'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function action(el){const a=el.dataset.platformAction;
    if(a==='go'){ui.query='';if(el.dataset.route==='roi')ui.document=null;L.router.go(el.dataset.route);}
    else if(a==='account')experience.openAccount(el.dataset.id);
    else if(a==='scenario'){ui.scenario=el.dataset.scenario;L.router.go('forecast');}
    else if(a==='pillar'){ui.pillar=Number(el.dataset.index);L.router.go('gtm');}
    else if(a==='move')moveDialog(el.dataset.id,el.dataset.type);
    else if(a==='close-dialog')document.getElementById('platformDialog')?.close();
    else if(a==='new-battlecard'){ui.document=null;L.router.go('battlecardEditor');}
    else if(a==='edit-battlecard'){ui.document=el.dataset.id;L.router.go('battlecardEditor');}
    else if(a==='open-roi'){ui.document=el.dataset.id;L.router.go('roi');}
    else if(a==='add-contact'||a==='edit-contact'){if(S.access.writeCRM)L.openContactModal(el.dataset.id);}
    else if(a==='add-activity'){if(S.access.writeCRM)L.openActivityModal();}
    else if(a==='export-document'){const d=S.documents.find(d=>d.id===el.dataset.id);download('tarkit-artifact.md',`# ${d.title}\n\n${d.local_draft?'Device draft':'Workspace artifact'}\n\n`+Object.entries(d.content).map(([k,v])=>`## ${k}\n\n${typeof v==='object'?JSON.stringify(v,null,2):v}`).join('\n\n'));}
    else if(a==='export-forecast'){const f=forecast(L.store.deals,ui.scenario);download('tarkit-forecast.csv',`Scenario,Month,Projected SAR,Cumulative SAR\n${f.buckets.map(b=>`${ui.scenario},${b.key},${b.value.toFixed(2)},${b.cumulative.toFixed(2)}`).join('\n')}`,'text/csv');}
  }
  async function submit(form){const values=Object.fromEntries(new FormData(form)),kind=form.dataset.platformForm;
    if(kind==='helper'){const q=normalizeName(values.question),m=metrics(L.store);const answers=[[/target|goal/,`Your annual target is ${money(L.store.targets.annual_sar)}. Won revenue this year is ${money(m.wonValue)}.`],[/customer|renewal|csm/,`${m.won.length} won contracts are available in Customer Success. ${S.customers.filter(c=>c.health==='At risk').length} have recorded at-risk health.`],[/data|quality|contact/,`Core-field completeness is ${pct(dataHealth(L.store).score)} across ${L.store.companies.length} companies and ${L.store.contacts.length} contacts.`],[/pipeline|revenue|deal|forecast/,`Open pipeline is ${money(m.pipeline)} across ${m.open.length} opportunities. Weighted pipeline is ${money(m.weighted)}.`],[/action|follow|meeting/,`${m.due.length} next actions are due today or overdue. Open Activities to follow through.`]];document.getElementById('helperAnswer').innerHTML=`<div class="notice-bar">${e(answers.find(([p])=>p.test(q))?.[1]||'Try asking about pipeline, targets, customers, next actions or data quality. This helper summarizes saved workspace facts.')}</div>`;return;}
    if(kind==='move'){
      const type=form.dataset.type,stages=type==='csm'?CSM_STAGES:L.stages;if(!S.access.writeCRM||!stages.find(s=>s.key===values.stage)?.subs.includes(values.sub_stage))throw new Error('Choose an allowed stage and sub-stage.');
      if(type==='csm')await service.saveCustomer({...values,deal_id:form.dataset.id,expected_updated_at:form.dataset.updated});
      else {let q=L.db.from('deals').update({stage:values.stage,sub_stage:values.sub_stage,probability:stages.find(s=>s.key===values.stage).probability}).eq('id',form.dataset.id).eq('stage',form.dataset.originalStage);q=form.dataset.originalSub?q.eq('sub_stage',form.dataset.originalSub):q.is('sub_stage',null);const {data,error}=await q.select('id').single();if(error||!data)throw new Error('The deal changed or could not be saved. Close this dialog and refresh before trying again.');await L.loadStore();}
      document.getElementById('platformDialog').close();L.toast('Stage and sub-stage saved');L.router.go(type);return;
    }
    if(kind==='access'){await service.saveAccess(form.dataset.user,values.role,values.app_role,new FormData(form).getAll('environment'));L.toast('Access updated');L.router.go('workspace');return;}
    if(kind==='target'){if(!S.access.writeStrategy)throw new Error('Your role cannot edit targets.');const amount=Number(values.amount);if(!Number.isFinite(amount)||amount<0)throw new Error('Enter a valid target.');const year=new Date().getFullYear();const existing=await L.db.from('annual_targets').select('id').eq('year',year).maybeSingle();if(existing.error)throw existing.error;const result=existing.data?await L.db.from('annual_targets').update({target_sar:amount}).eq('id',existing.data.id):await L.db.from('annual_targets').insert({year,target_sar:amount});if(result.error)throw result.error;await L.loadStore();L.toast('Annual target saved');return;}
    let artifact;
    if(kind==='gtm'){const d=docOf('gtm');artifact={id:d?.id,kind:'gtm',title:'GTM Strategy',content:{...d?.content,[PILLARS[ui.pillar]]:values.body}};}
    if(kind==='vision'){artifact={id:docOf('vision')?.id,kind:'vision',title:'Vision & Targets',content:{body:values.body}};}
    if(kind==='motions'){const mix=MOTIONS.map((_,i)=>Number(values[`mix${i}`]));if(mix.some(v=>!Number.isFinite(v)||v<0||v>100)||mix.reduce((s,v)=>s+v,0)!==100)throw new Error('Allocate exactly 100% across the four growth motions.');artifact={id:docOf('motions')?.id,kind:'motions',title:'GTM Motions Mix',content:{mix,notes:MOTIONS.map((_,i)=>values[`note${i}`])}};}
    if(kind==='battlecard'){if(!values.title.trim())throw new Error('Enter a title.');const {title,...content}=values;artifact={id:ui.document,kind:'battlecard',title:title.trim(),content};}
    if(kind==='roi'){roi(values);const {title,...content}=values;artifact={id:ui.document,kind:'roi',title:title.trim(),content};}
    if(artifact){const d=await service.saveDocument(artifact);if(['roi','battlecard'].includes(artifact.kind))ui.document=d.id;L.toast(S.ready?'Workspace changes saved':'Draft saved on this device');}
  }
  function install(){
    L.store.ui.collapsedSections.command=false;
    Object.assign(L.routes,{home:{title:'Command Center',render:home},reportCRM:{title:'CRM Analytics',render:crmAnalytics},reportCSM:{title:'CSM Analytics',render:csmAnalytics},reportActivity:{title:'Activities Momentum',render:activitiesAnalytics},reportCC:{title:'Data Health',render:healthPage},helper:{title:'iHelper',render:helperPage},forecast:{title:'Revenue Forecast',render:forecastPage},crm:{title:'CRM',render:p=>board(p,'crm')},csm:{title:'CSM',render:p=>board(p,'csm')},gtm:{title:'GTM Strategy',render:gtmPage},motions:{title:'GTM Motions Mix',render:motionsPage},battlecards:{title:'Battlecards',render:battlecardsPage},battlecardEditor:{title:'Battlecard',render:battlecardEditor},roi:{title:'ROI & Case Studies',render:roiPage},target:{title:'Vision & Targets',render:targetPage},stakeholders:{title:'Stakeholders',render:p=>peoplePage(p,true)},people:{title:'Contacts',render:p=>peoplePage(p)},activities:{title:'Activities',render:activitiesPage},workspace:{title:'Team & Workspace',render:workspacePage}});
    L.nav.splice(0,L.nav.length,...routeGroups.map(g=>({...g,items:g.items.map(([key,label,symbol])=>({key,label,tip:label,icon:icon(symbol)}))})));
    const priorGo=L.router.go.bind(L.router);L.router.go=key=>{if(!allowedRoute(key))key='home';if(!S.access.writeCRM&&['newCompany','newOpportunity','newFollowup','importCompanies'].includes(key))key='home';if(!S.access.admin&&['settings','integrations'].includes(key))key='workspace';priorGo(key);shell();};
    document.getElementById('environmentSelect').addEventListener('change',event=>{service.switchEnvironment(event.target.value);L.router.go('home');});
    document.getElementById('globalSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();ui.query=event.target.value;L.router.go('search');}});
    L.routes.search={title:'Search',render:target=>{const q=normalizeName(ui.query),rows=L.store.companies.filter(c=>normalizeName(c.name).includes(q));target.innerHTML=head('Search results',`Companies matching “${ui.query}”`)+`<section class="panel">${rows.map(c=>`<div class="work-row"><div><strong>${e(c.name)}</strong><small>${e(c.country||'Country not set')}</small></div>${act('Open account','account',`data-id="${e(c.id)}"`)}</div>`).join('')||empty('No matching companies','Try another company name.')}</section>`;}};
    document.getElementById('globalSearch').placeholder='Search companies · Enter';
    document.addEventListener('click',event=>{const el=event.target.closest('[data-platform-action]');if(el&&!el.disabled){event.preventDefault();event.stopPropagation();action(el).then(refreshIcons).catch(error=>L.toast(error.message,'danger'));}},true);
    document.addEventListener('submit',async event=>{const form=event.target;if(!form.matches('[data-platform-form]'))return;event.preventDefault();event.stopImmediatePropagation();if(form.dataset.busy)return;form.dataset.busy='1';const b=form.querySelector('[type="submit"],button:not([type])'),msg=form.querySelector('[data-platform-error]'),label=b?.textContent;if(b){b.disabled=true;b.textContent='Saving…';}if(msg)msg.textContent='';try{await submit(form);}catch(error){if(msg)msg.textContent=error.message;else L.toast(error.message,'danger');}finally{delete form.dataset.busy;if(b?.isConnected){b.disabled=false;b.textContent=label;}}},true);
    page().addEventListener('input',event=>{if(event.target.matches('[data-roi-input]'))updateROI();if(event.target.matches('.mix-input')){const sum=[...page().querySelectorAll('.mix-input')].reduce((s,el)=>s+Number(el.value),0);document.getElementById('mixTotal').textContent=`Total allocation: ${sum}% · Must equal 100% to save.`;}if(event.target.id==='platformPeopleSearch'){ui.query=event.target.value;const pos=event.target.selectionStart;peoplePage(page(),L.router.current==='stakeholders');const input=document.getElementById('platformPeopleSearch');input.focus();input.setSelectionRange(pos,pos);refreshIcons();}});
    page().addEventListener('dragstart',event=>{const card=event.target.closest('.revenue-card');if(!card||!S.access.writeCRM){event.preventDefault();return;}ui.drag={id:card.dataset.deal,type:card.closest('[data-board]').dataset.board};event.dataTransfer.setData('text/plain',card.dataset.deal);event.dataTransfer.effectAllowed='move';card.classList.add('is-dragging');});
    page().addEventListener('dragover',event=>{if(ui.drag&&event.target.closest('[data-drop-stage]'))event.preventDefault();});
    page().addEventListener('drop',event=>{const col=event.target.closest('[data-drop-stage]');if(!ui.drag||!col)return;event.preventDefault();const {id,type}=ui.drag;ui.drag=null;moveDialog(id,type,col.dataset.dropStage);});
    page().addEventListener('dragend',()=>{ui.drag=null;page().querySelectorAll('.is-dragging').forEach(c=>c.classList.remove('is-dragging'));});
  }
  return {install,initialize:service.initialize,state:S,service};
}
